const fallbackCar="https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85";

const img = {
  xuv:"https://media.zigcdn.com/media/model/2026/Jan/mahindra_xuv_7xo.jpg",
  xuvBlack:"https://media.zigcdn.com/media/model/2026/Jan/model-extimg-1113103544_600x400.jpg",
  seltos:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2026_Kia_Seltos.jpg",
  creta:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Hyundai_Creta_1.5_Plus_2024.jpg",
  syros:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2025_Kia_Syros_1.5_HTX%2B_%28O%29_%28India%29_front_view_01.jpg",
  hyryder:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Urban_Cruiser_Hyryder.jpg",
  verna:"https://commons.wikimedia.org/wiki/Special:Redirect/file/0_Hyundai_Verna_%28MC%29_1.jpg",
  xuv700:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2023_Mahindra_XUV700_AX7L_front.jpg",
  syrosInterior:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2025_Kia_Syros_1.5_HTX%2B_%28O%29_%28India%29_interior.png",
  cretaInterior:"https://cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/VGVSDSS5YVGXVMG7ZXVNY42UCE.JPG",
  xuvInterior:"https://www.autocarindia.com/auto-images/mahindra-xuv-7xo-interior-gallery-439964",
  tharOg:"https://www.autocarindia.com/cars/mahindra/thar-og/images/front-left-three-quarter",
  tharOgInterior:"https://www.autox.com/news/car-news/2026-mahindra-thar-facelift-launched-in-india-at-rs-1032-lakh-124632/",
  nexon:"https://i.cdn.newsbytesapp.com/images/l144_8811775567095.jpg",
  classic350:"https://imgcdn.oto.com/large/gallery/exterior/100/1536/royal-enfield-classic-350-left-side-view-full-image-749296.jpg",
  duke390:"https://asset.autocarindia.com/static/models/colors/20260421_113328_27323983.webp?w=1200",
  r15:"https://auto.hindustantimes.com/_next/image?q=75&url=https%3A%2F%2Fhtcms-prod-images.s3.ap-south-1.amazonaws.com%2Fhtmobile1%2Fyamaha_r15v4%2Fimages%2Fcolours_yamaha-r15v4_white-metallic_930x620.jpg&w=1200",
  glanza:"https://cdn-s3.autocarindia.com/legacy/cdni/mmv_images/colors/20250610052632_Toyota_Glanza_Insta_Blue%5B1%5D.jpg?q=75&w=900",
  taisor:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Front_view_of_Toyota_Urban_Cruiser_Taisor.jpg",
  innovaCrysta:"https://cdn.langit7.id/foto/1200/langit7/berita/2025/12/30/1/54079/toyota-innova-crysta-2026-diluncurkan-dengan-mesin-diesel-kuat-kenyamanan-7-penumpang-mewah--kabin-luas-bnx.jpeg",
  innovaHycross:"https://carbikegpt.com/wp-content/uploads/2025/11/toyota-innova-hycross.jpg",
  fortuner:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Fortuner_Full_cropped.jpg",
  camry:"https://www.v3cars.com/media/model-imgs/878615red.webp",
  hilux:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Hilux_8th_generation.jpg",
  rumion:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Rumion.jpg",
  vellfire:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Vellfire_2024.jpg",
  landcruiser300:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Land_Cruiser_300.jpg",
  ebella:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota_Urban_Cruiser_Ebella.jpg"
};

const vehicles=[
{id:"xuv7xo",type:"car",brand:"Mahindra",name:"XUV 7XO",category:"SUV",year:2026,badge:"LATEST 2026",price:"₹13.66 Lakh*",image:img.xuv,gallery:[img.xuv,img.xuvBlack],colors:[["Everest White","#f4f4ef"],["Midnight Black","#15171a"],["Stealth Black","#292b2f"],["Galaxy Grey","#71757a"],["Nebula Blue","#254d78"],["Ruby Velvet","#6d2730"]],engines:["2.0L Turbo Petrol • 200 PS • 380 Nm","2.2L Turbo Diesel • 185 PS • 420–450 Nm"],fuel:"Petrol / Diesel",transmission:"6-speed MT / 6-speed AT",drive:"FWD / AWD (diesel)",seats:"6 / 7",mileage:"Up to 15.5 km/l (claimed)",length:"4695 mm",wheelbase:"2750 mm",features:["Coast-to-coast triple HD screens","540° surround-view camera","ADAS Level 2","16-speaker Harman Kardon + Dolby Atmos","DAVINCI suspension","Panoramic Skyroof"],official360:"https://auto.mahindra.com/360-view?cid=XUV7XO",source:"Mahindra's 2026 launch information and official 360 configurator."},
{id:"seltos",type:"car",brand:"Kia",name:"Seltos",category:"SUV",year:2026,badge:"NEW GENERATION",price:"₹15.29 Lakh*",image:img.seltos,gallery:[img.seltos],colors:[["Glacier White","#e9edf0"],["Gravity Grey","#73777c"],["Imperial Blue","#173f68"],["Magma Red","#9c2b29"],["Aurora Black","#111316"],["Pewter Olive","#777a61"],["Frost Blue","#b8d0db"]],engines:["1.5L Petrol • 115 PS","1.5L Turbo Petrol • 160 PS","1.5L Diesel • 116 PS"],fuel:"Petrol / Diesel",transmission:"6MT / 6AT / 7DCT / IVT",drive:"FWD",seats:"5",mileage:"Variant dependent",length:"4460 mm",wheelbase:"2690 mm",features:["ADAS Level 2 with 21 functions","360° camera","Dual-pane panoramic sunroof","12.3-inch HD display","Ventilated front seats","Digital key"],official360:"https://www.kia.com/in/our-vehicles/seltos/showroom.html",source:"Kia India's current Seltos showroom/specification pages."},
{id:"creta",type:"car",brand:"Hyundai",name:"Creta",category:"SUV",year:2026,badge:"POPULAR SUV",price:"₹11.11 Lakh*",image:img.creta,gallery:[img.creta,img.cretaInterior],colors:[["Atlas White","#f3f3f1"],["Fiery Red","#9d2729"],["Abyss Black","#101215"],["Titan Grey","#6f7378"],["Ranger Khaki","#6e715f"],["Robust Emerald","#17664f"]],engines:["1.5L MPI Petrol • 116 PS","1.5L Turbo GDi Petrol • 160 PS","1.5L U2 CRDi Diesel • 116 PS"],fuel:"Petrol / Diesel",transmission:"6MT / IVT / 7DCT / 6AT",drive:"FWD",seats:"5",mileage:"Up to 21.8 km/l* (variant dependent)",length:"4330 mm",wheelbase:"2610 mm",features:["10.25-inch infotainment + digital cluster","ADAS on higher trims","Panoramic sunroof","Bose premium audio","Ventilated seats","Bluelink connected car"],official360:"https://www.hyundai.com/in/en/find-a-car/creta/exterior",interiorUrl:"https://www.hyundai.com/in/en/find-a-car/creta/interior",source:"Hyundai India's 2026 Creta pages."},
{id:"syros",type:"car",brand:"Kia",name:"Syros",category:"SUV",year:2026,badge:"POPULAR",price:"₹9.00 Lakh*",image:img.syros,gallery:[img.syros,img.syrosInterior],colors:[["Aurora Black","#101216"],["Glacier White","#edf0f0"],["Magma Red","#982b2c"],["Frost Blue","#a8c8d5"],["Pewter Olive","#777a63"]],engines:["1.0L Turbo Petrol • 120 PS","1.5L Turbo Diesel • 116 PS"],fuel:"Petrol / Diesel",transmission:"6MT / 7DCT / 6AT",drive:"FWD",seats:"5",mileage:"Variant dependent",length:"3995 mm",wheelbase:"2550 mm",features:["Panoramic sunroof","Ventilated seats","360° camera on select trims","ADAS on select trims","Dual-screen cockpit","Level 2 ADAS available"],source:"Kia Syros model data; verify final variant equipment before publishing."},
{id:"hyryder",type:"car",brand:"Toyota",name:"Urban Cruiser Hyryder",category:"SUV",year:2026,badge:"HYBRID",price:"₹10.94 Lakh*",image:img.hyryder,gallery:[img.hyryder],colors:[["White","#e8e8e5"],["Silver","#a8abb0"],["Black","#111"],["Red","#a52627"]],engines:["1.5L Strong Hybrid • 116 PS system","1.5L K-Series Neo Drive • 103 PS"],fuel:"Petrol / Strong Hybrid / CNG",transmission:"5MT / 6AT / e-Drive",drive:"2WD / AWD (select)",seats:"5",mileage:"Up to 27.97 km/l* hybrid",length:"4365 mm",wheelbase:"2600 mm",features:["Strong self-charging hybrid","360° camera","Panoramic sunroof","Ventilated seats","6 airbags","Connected infotainment"],source:"Toyota Bharat 2026 information."},
{id:"verna",type:"car",brand:"Hyundai",name:"Verna",category:"Sedan",year:2026,badge:"SEDAN",price:"₹10.99 Lakh*",image:img.verna,gallery:[img.verna],colors:[["Atlas White","#eee"],["Fiery Red","#8f2729"],["Abyss Black","#111"],["Titan Grey","#72767a"]],engines:["1.5L MPI Petrol • 115 PS","1.5L Turbo Petrol • 160 PS"],fuel:"Petrol",transmission:"6MT / IVT / 7DCT",drive:"FWD",seats:"5",mileage:"Up to 20.6 km/l*",length:"4535 mm",wheelbase:"2670 mm",features:["ADAS Level 2","Ventilated seats","Electric sunroof","10.25-inch screens","Bose audio","Front parking sensors"],source:"Hyundai India current Verna range."},
{id:"xuv700",type:"car",brand:"Mahindra",name:"XUV700",category:"SUV",year:2026,badge:"FAMILY SUV",price:"₹14.49 Lakh*",image:img.xuv700,gallery:[img.xuv700],colors:[["White","#eee"],["Black","#111"],["Red","#70282d"],["Silver","#a6a9ad"]],engines:["2.0L Turbo Petrol • 200 PS","2.2L Turbo Diesel • up to 185 PS"],fuel:"Petrol / Diesel",transmission:"6MT / 6AT",drive:"FWD / AWD (select diesel)",seats:"5 / 7",mileage:"Variant dependent",length:"4695 mm",wheelbase:"2750 mm",features:["ADAS","Panoramic skyroof","7 airbags","Connected car tech","360° camera on select trims","Dual-screen cockpit"],source:"Mahindra model information; pricing varies by variant."},
{id:"glanza",type:"car",brand:"Toyota",name:"Glanza",category:"Hatchback",year:2026,badge:"HATCHBACK",price:"₹6.73 Lakh*",image:img.glanza,gallery:[img.glanza],colors:[["Insta Blue","rgb(39,83,153)"],["Gaming Grey","rgb(96,102,108)"],["Enticing Silver","rgb(170,175,180)"],["Sportin Red","rgb(151,35,38)"],["Cafe White","rgb(238,238,232)"]],engines:["1.2L Petrol • 90 PS • 113 Nm","1.2L CNG • 78 PS • 98.5 Nm"],fuel:"Petrol / CNG",transmission:"5MT / AMT",drive:"FWD",seats:"5",mileage:"22.35–30.61 km/kg*",length:"3990 mm",wheelbase:"2520 mm",features:["360° parking camera","9-inch SmartPlaycast","HUD","6 airbags","Toyota i-Connect"],official360:"https://www.toyotabharat.com/showroom/glanza/",source:"Toyota Bharat current Glanza range."},
{id:"taisor",type:"car",brand:"Toyota",name:"Urban Cruiser Taisor",category:"SUV",year:2026,badge:"COMPACT SUV",price:"₹7.43 Lakh*",image:img.taisor,gallery:[img.taisor],colors:[["Sportin Red","rgb(150,35,40)"],["Enticing Silver","rgb(165,170,175)"],["Lucent Orange","rgb(190,75,30)"],["Cafe White","rgb(238,238,232)"],["Gaming Grey","rgb(90,96,102)"]],engines:["1.2L Petrol • 90 PS","1.0L Turbo Petrol • 100 PS"],fuel:"Petrol / CNG",transmission:"5MT / AMT / 6AT",drive:"FWD",seats:"5",mileage:"Variant dependent",length:"3995 mm",wheelbase:"2520 mm",features:["LED lighting","9-inch touchscreen","Head-up display","6 airbags","Connected features"],official360:"https://www.toyotabharat.com/showroom/taisor/",source:"Toyota Bharat current Taisor range."},
{id:"rumion",type:"car",brand:"Toyota",name:"Rumion",category:"MPV",year:2026,badge:"MPV",price:"₹9.79 Lakh*",image:img.rumion,gallery:[img.rumion],colors:[["White","rgb(238,238,232)"],["Silver","rgb(170,175,180)"],["Red","rgb(140,35,40)"]],engines:["1.5L Petrol • 103 PS","1.5L CNG • 88 PS"],fuel:"Petrol / CNG",transmission:"5MT / 6AT",drive:"FWD",seats:"7",mileage:"Up to 26.11 km/kg* CNG",length:"4420 mm",wheelbase:"2740 mm",features:["7 seats","Toyota warranty","Connected infotainment","Rear AC vents"],official360:"https://www.toyotabharat.com/showroom/rumion/",source:"Toyota Bharat current Rumion range."},
{id:"innovacrysta",type:"car",brand:"Toyota",name:"Innova Crysta",category:"MPV",year:2026,badge:"FAMILY MPV",price:"₹19.72 Lakh*",image:img.innovaCrysta,gallery:[img.innovaCrysta],colors:[["Super White","rgb(240,240,235)"],["Silver","rgb(165,168,172)"],["Attitude Black","rgb(20,20,22)"]],engines:["2.4L Diesel • 150 PS • 343 Nm"],fuel:"Diesel",transmission:"5-speed Manual",drive:"RWD",seats:"7 / 8",mileage:"Variant dependent",length:"4735 mm",wheelbase:"2750 mm",features:["7/8 seats","Power modes","Connected infotainment","Toyota safety"],official360:"https://tweb.toyotabharat.com/innova-crysta.html",source:"Toyota Bharat current Innova Crysta page."},
{id:"innovahycross",type:"car",brand:"Toyota",name:"Innova Hycross",category:"MPV",year:2026,badge:"HYBRID MPV",price:"₹19.53 Lakh*",image:img.innovaHycross,gallery:[img.innovaHycross],colors:[["Black","rgb(20,23,27)"],["White","rgb(238,238,235)"],["Silver","rgb(165,170,175)"]],engines:["2.0L Petrol • 174 PS","2.0L Strong Hybrid • 186 PS system"],fuel:"Petrol / Strong Hybrid",transmission:"e-CVT / Automatic",drive:"FWD",seats:"7 / 8",mileage:"Hybrid variant dependent",length:"4755 mm",wheelbase:"2850 mm",features:["Powered ottoman seats","Panoramic sunroof","Toyota Safety Sense","ADAS","Hybrid system"],official360:"https://www.toyotabharat.com/showroom/innova-hycross/",source:"Toyota Bharat current Innova Hycross range."},
{id:"hilux",type:"car",brand:"Toyota",name:"Hilux",category:"Pickup",year:2026,badge:"PICKUP",price:"₹31.99 Lakh*",image:img.hilux,gallery:[img.hilux],colors:[["White","rgb(238,238,235)"],["Silver","rgb(160,165,170)"],["Black","rgb(20,20,22)"]],engines:["2.8L Diesel • 204 PS • 420–500 Nm"],fuel:"Diesel",transmission:"6MT / 6AT",drive:"4WD",seats:"5",mileage:"Variant dependent",length:"5325 mm",wheelbase:"3085 mm",features:["4WD","High ground clearance","Pickup bed","Off-road capability"],official360:"https://www.toyotabharat.com/showroom/hilux/",source:"Toyota Bharat current Hilux range."},
{id:"fortuner",type:"car",brand:"Toyota",name:"Fortuner",category:"SUV",year:2026,badge:"ICONIC SUV",price:"₹34.76 Lakh*",image:img.fortuner,gallery:[img.fortuner],colors:[["Attitude Black","rgb(20,20,22)"],["Super White","rgb(240,240,235)"],["Silver Metallic","rgb(165,168,172)"],["Phantom Brown","rgb(88,62,50)"],["Platinum White Pearl","rgb(235,235,230)"]],engines:["2.7L Petrol • 166 PS","2.8L Turbo Diesel • 204 PS • 500 Nm"],fuel:"Petrol / Diesel",transmission:"5MT / 6MT / 6AT",drive:"RWD / 4WD",seats:"7",mileage:"10.26–14.4 km/l*",length:"4795 mm",wheelbase:"2745 mm",features:["4WD","Downhill assist","360° camera","JBL audio","Ventilated seats"],official360:"https://www.toyotabharat.com/showroom/fortuner/",source:"Toyota Bharat and current 2026 Fortuner data."},
{id:"legender",type:"car",brand:"Toyota",name:"Fortuner Legender",category:"SUV",year:2026,badge:"PREMIUM SUV",price:"₹50.87 Lakh*",image:img.fortuner,gallery:[img.fortuner],colors:[["Avant Garde Bronze","rgb(115,74,42)"],["White","rgb(240,240,235)"],["Black","rgb(20,20,22)"]],engines:["2.8L Diesel • 204 PS • 500 Nm"],fuel:"Diesel",transmission:"6MT / 6AT",drive:"RWD / 4WD",seats:"7",mileage:"Variant dependent",length:"4795 mm",wheelbase:"2745 mm",features:["Powered tailgate","Wireless charging","Navigation","360° camera","Premium exterior"],official360:"https://www.toyotabharat.com/showroom/fortuner/",source:"Toyota Fortuner Legender range."},
{id:"camry",type:"car",brand:"Toyota",name:"Camry",category:"Sedan",year:2026,badge:"HYBRID SEDAN",price:"₹47.48 Lakh*",image:img.camry,gallery:[img.camry],colors:[["Emotional Red","rgb(160,30,34)"],["Attitude Black","rgb(20,20,22)"],["Cement Grey","rgb(125,130,135)"],["Platinum White","rgb(238,238,235)"]],engines:["2.5L Petrol Hybrid • 230 PS system"],fuel:"Petrol Hybrid",transmission:"e-CVT",drive:"FWD",seats:"5",mileage:"25.49 km/l*",length:"4920 mm",wheelbase:"2825 mm",features:["Hybrid powertrain","ADAS","Premium JBL audio","Ventilated seats","Panoramic roof"],official360:"https://www.toyotabharat.com/showroom/camry/",source:"Toyota Bharat current Camry range."},
{id:"vellfire",type:"car",brand:"Toyota",name:"Vellfire",category:"MPV",year:2026,badge:"LUXURY MPV",price:"₹1.20 Crore*",image:img.vellfire,gallery:[img.vellfire],colors:[["White","rgb(240,240,235)"],["Black","rgb(20,20,22)"],["Silver","rgb(165,168,172)"]],engines:["2.5L Petrol Hybrid"],fuel:"Petrol Hybrid",transmission:"e-CVT",drive:"FWD",seats:"7",mileage:"Hybrid dependent",length:"4995 mm",wheelbase:"3000 mm",features:["Executive captain seats","Power ottoman","Premium cabin","Toyota Safety Sense"],official360:"https://www.toyotabharat.com/showroom/vellfire/",source:"Toyota Bharat current Vellfire range."},
{id:"lc300",type:"car",brand:"Toyota",name:"Land Cruiser 300",category:"SUV",year:2026,badge:"FLAGSHIP",price:"₹2.18 Crore*",image:img.landcruiser300,gallery:[img.landcruiser300],colors:[["White","rgb(240,240,235)"],["Black","rgb(20,20,22)"],["Silver","rgb(165,168,172)"]],engines:["3.3L Twin-Turbo Diesel • 309 PS"],fuel:"Diesel",transmission:"10-speed Automatic",drive:"4WD",seats:"7",mileage:"Variant dependent",length:"4985 mm",wheelbase:"2850 mm",features:["Full-time 4WD","Multi-Terrain Select","Premium leather cabin","ADAS"],official360:"https://www.toyotabharat.com/showroom/land-cruiser-300/",source:"Toyota Bharat current Land Cruiser 300 range."},
{id:"ebella",type:"car",brand:"Toyota",name:"Urban Cruiser Ebella",category:"EV",year:2026,badge:"ELECTRIC SUV",price:"₹23.60 Lakh*",image:img.ebella,gallery:[img.ebella],colors:[["White","rgb(240,240,235)"],["Blue","rgb(60,105,150)"],["Black","rgb(20,20,22)"]],engines:["Electric powertrain • battery dependent"],fuel:"Electric",transmission:"Single-speed",drive:"FWD",seats:"5",mileage:"Range dependent",length:"—",wheelbase:"—",features:["Electric powertrain","Connected tech","Modern cabin","Safety suite"],official360:"https://www.toyotabharat.com/showroom/urban-cruiser-ebella/",source:"Toyota Bharat current Urban Cruiser Ebella range."},
{id:"cretaev",type:"car",brand:"Hyundai",name:"Creta Electric",category:"EV",year:2026,badge:"ELECTRIC",price:"₹17.99 Lakh*",image:img.creta,gallery:[img.creta,img.cretaInterior],colors:[["White","#eee"],["Blue","#477da2"],["Black","#111"],["Silver","#9ca2a7"]],engines:["42 kWh battery • up to 138 PS","51.4 kWh battery • up to 171 PS"],fuel:"Electric",transmission:"Single-speed",drive:"FWD",seats:"5",mileage:"Up to 473 km claimed range*",length:"4340 mm",wheelbase:"2610 mm",features:["Vehicle-to-load","ADAS","360° camera","Dual 10.25-inch displays","Fast charging","EV-specific cabin"],official360:"https://www.hyundai.com/in/en/find-a-car/creta-electric/exterior",interiorUrl:"https://www.hyundai.com/in/en/find-a-car/creta-electric/interior",source:"Hyundai India Creta Electric pages."},
{id:"thar",type:"car",brand:"Mahindra",name:"Thar OG",category:"SUV",year:2026,badge:"JUST LAUNCHED",price:"₹10.32 Lakh*",image:img.tharOg,gallery:[img.tharOg],colors:[["Tango Red","#9a2c2d"],["Jeans Blue","#31597d"],["Stealth Black","#111"],["Galaxy Grey","#777"],["Everest White","#eee"],["Deep Forest","#405844"],["Battleship Grey","#555"],["Artemis Silver","#aeb2b5"]],engines:["1.5L Diesel • 119 PS • RWD","2.0L Turbo Petrol • 152 PS • RWD / 4WD","2.2L Turbo Diesel • 132 PS • RWD / 4WD"],fuel:"Petrol / Diesel",transmission:"6MT / 6AT",drive:"RWD / 4WD",seats:"4",mileage:"Variant dependent",length:"3995 mm",wheelbase:"2450 mm",features:["M_Glyde 4G platform","PENTALINK suspension","DAVINCI damping","Electronic locking differential","Terrain modes","6 airbags + all-disc brakes","R19 alloys on ZXT"],official360:"https://auto.mahindra.com/own-online/variant-selection?pid=X7XOM095618025502",source:"Mahindra launched the Thar OG on 22 September 2026 at ₹10.32 lakh ex-showroom; deliveries begin 11 October 2026."},
{id:"nexon",type:"car",brand:"Tata",name:"Nexon",category:"SUV",year:2026,badge:"BESTSELLER",price:"₹8.00 Lakh*",image:img.nexon,gallery:[img.nexon],colors:[["White","#eee"],["Grey","#777"],["Blue","#315d9b"],["Red","#a32b2b"]],engines:["1.2L Turbo Petrol","1.5L Turbo Diesel","Electric variants available"],fuel:"Petrol / Diesel / EV",transmission:"MT / AMT / DCT / EV",drive:"FWD",seats:"5",mileage:"Variant dependent",length:"3995 mm",wheelbase:"2498 mm",features:["10.25-inch infotainment","360° camera on select trims","Sunroof","ADAS on select trims","Connected tech","Multiple powertrains"],source:"Indicative current-range data."}
];

const bikes=[
{id:"classic350",type:"bike",brand:"Royal Enfield",name:"Classic 350",category:"Bike",year:2026,badge:"ICON",price:"₹1.93 Lakh*",image:img.classic350,gallery:[img.classic350],colors:[["Black","#111"],["Green","#405b43"],["Red","#9c282b"],["Chrome","#c3c5c7"]],engines:["349cc single-cylinder • 20.2 PS • 27 Nm"],fuel:"Petrol",transmission:"5-speed",drive:"Chain",seats:"2",mileage:"~41 km/l*",length:"2145 mm",wheelbase:"1390 mm",features:["Dual-channel ABS","Tripper navigation on select trims","LED lighting on select trims","Classic metal design"],source:"Indicative current-range data."},
{id:"hunter350",type:"bike",brand:"Royal Enfield",name:"Hunter 350",category:"Bike",year:2026,badge:"STREET",price:"₹1.50 Lakh*",image:img.classic350,gallery:[img.classic350],colors:[["Black","#111"],["Red","#9a2528"],["Grey","#777"],["Blue","#31567e"]],engines:["349cc single-cylinder • 20.2 PS • 27 Nm"],fuel:"Petrol",transmission:"5-speed",drive:"Chain",seats:"2",mileage:"~36 km/l*",length:"2055 mm",wheelbase:"1370 mm",features:["Lightweight roadster","Dual-channel ABS","LED headlamp on select trims","Ride-by-wire style urban response"],source:"Indicative current-range data."},
{id:"duke390",type:"bike",brand:"KTM",name:"390 Duke",category:"Bike",year:2026,badge:"PERFORMANCE",price:"₹2.95 Lakh*",image:img.duke390,gallery:[img.duke390],colors:[["Orange","#e46d21"],["Black","#111"],["Grey","#777"]],engines:["399cc single-cylinder • 46 PS • 39 Nm"],fuel:"Petrol",transmission:"6-speed",drive:"Chain",seats:"2",mileage:"~30 km/l*",length:"-",wheelbase:"1357 mm",features:["Ride modes","Cornering ABS","Traction control","Quickshifter+","TFT display"],source:"Indicative current-range data."},
{id:"r15",type:"bike",brand:"Yamaha",name:"R15 V4",category:"Bike",year:2026,badge:"SPORT",price:"₹1.84 Lakh*",image:img.r15,gallery:[img.r15],colors:[["Blue","#244f8e"],["Black","#111"],["Red","#9c2727"]],engines:["155cc liquid-cooled • 18.4 PS • 14.2 Nm"],fuel:"Petrol",transmission:"6-speed",drive:"Chain",seats:"2",mileage:"~47 km/l*",length:"1990 mm",wheelbase:"1325 mm",features:["VVA engine","Assist & slipper clutch","Traction control","Dual-channel ABS","Deltabox frame"],source:"Indicative current-range data."}
];

let currentFilter="all", compareIds=[];

function safeImage(el){el.onerror=()=>{el.onerror=null;el.src=fallbackCar}}
function money(v){return v||"Price on request"}

function card(v){
 return `<article class="vehicle-card" data-id="${v.id}" data-type="${v.category}" data-name="${(v.brand+" "+v.name).toLowerCase()}">
   <div class="vehicle-image"><img src="${v.image}" alt="${v.brand} ${v.name}" onerror="safeImage(this)"><span class="badge">${v.badge}</span><button class="heart" onclick="toggleFavourite('${v.id}',this)">♡</button></div>
   <div class="vehicle-body"><h3>${v.brand} ${v.name}</h3><div class="meta">${v.year} • ${v.category} • ${v.fuel}</div>
   <div class="spec-row"><div class="spec"><b>${v.engines[0].split("•")[0]}</b><span>Engine</span></div><div class="spec"><b>${v.transmission}</b><span>Gearbox</span></div><div class="spec"><b>${v.seats}</b><span>Seats</span></div></div>
   <div class="price">${money(v.price)}</div><div class="actions"><button class="primary" onclick="openVehicle('${v.id}')">View Details</button><button onclick="addCompare('${v.id}')">Compare</button></div></div>
 </article>`
}

function render(){
 const cars=vehicles.filter(v=>currentFilter==="all"||v.category===currentFilter);
 document.getElementById("vehicleGrid").innerHTML=cars.map(card).join("");
 document.getElementById("latestGrid").innerHTML=vehicles.filter(v=>v.year>=2026).slice(0,8).map(card).join("");
 document.getElementById("bikeGrid").innerHTML=bikes.map(card).join("");
 renderBrands(); renderCompare();
}
function renderBrands(){
 const brands=[...new Set([...vehicles,...bikes].map(v=>v.brand))].sort();
 document.getElementById("brandGrid").innerHTML=brands.map(b=>`<button class="brand-btn" onclick="filterByBrand('${b}')"><span class="brand-mark">${b.split(" ").map(x=>x[0]).join("").slice(0,2)}</span>${b}</button>`).join("");
}
function setFilter(f,btn){currentFilter=f;document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));if(btn)btn.classList.add("active");document.getElementById("cars").scrollIntoView({behavior:"smooth"});render()}
function showAll(){currentFilter="all";render()}
function filterByBrand(brand){document.getElementById("searchInput").value=brand;searchVehicles()}
function quickSearch(q){document.getElementById("searchInput").value=q;searchVehicles()}
function focusSearch(){document.getElementById("searchInput").focus();window.scrollTo({top:0,behavior:"smooth"})}
function searchVehicles(){
 const q=document.getElementById("searchInput").value.trim().toLowerCase();
 if(!q){render();return}
 const all=[...vehicles,...bikes].filter(v=>{
   const text=[v.brand,v.name,v.category,v.fuel,v.badge,...v.engines].join(" ").toLowerCase();
   return text.includes(q);
 });
 const heading=document.querySelector("#cars h2");
 if(heading) heading.textContent=all.length?`Search results for “${document.getElementById("searchInput").value.trim()}” (${all.length})`:"No vehicles found";
 document.getElementById("vehicleGrid").innerHTML=all.length?all.map(card).join(""):`<div style="grid-column:1/-1;padding:60px;text-align:center;color:#aab6c5"><h3>No vehicle found</h3><p>Try Toyota, Mahindra, Hyundai, Kia, Creta, XUV 7XO, Seltos, Thar or KTM.</p></div>`;
 document.getElementById("cars").scrollIntoView({behavior:"smooth"});
}

function getVehicle(id){return [...vehicles,...bikes].find(v=>v.id===id)}
function openVehicle(id){
 const v=getVehicle(id); if(!v)return;
 const swatches=v.colors.map((c,i)=>`<button title="${c[0]}" class="swatch ${i===0?"active":""}" style="background:${c[1]}" onclick="selectColor(this,'${c[0]}')"></button>`).join("");
 document.getElementById("modalContent").innerHTML=`
 <div class="detail-top">
  <div class="detail-media"><div class="detail-main" id="detailStage"><img id="detailMainImage" src="${v.gallery[0]}" alt="${v.brand} ${v.name}" onerror="safeImage(this)"><span id="colorOverlay" class="color-overlay"></span><div class="stage-label">${v.official360?"360° VIEW AVAILABLE":"PHOTO GALLERY"}</div></div><div class="spin-hint">Select a colour to preview it on the vehicle. For a true interactive 360° experience, use the manufacturer viewer below.</div><div class="thumbs">${v.gallery.map((g,i)=>`<button class="${i===0?"active":""}" onclick="changeDetailImage('${g}',this)"><img src="${g}" onerror="safeImage(this)"></button>`).join("")}</div></div>
  <div class="detail-info"><div class="tag">${v.badge} • ${v.year}</div><h2>${v.brand} ${v.name}</h2><div class="meta">${v.category} • ${v.fuel} • ${v.seats} seats</div><div class="detail-price">${money(v.price)}</div>
   <div class="option-title">COLOUR</div><div class="swatches">${swatches}</div><div id="selectedColor" class="meta" style="margin-top:9px">Selected: ${v.colors[0][0]}</div>
   <div class="option-title">ENGINE / POWERTRAIN</div><select class="select">${v.engines.map(x=>`<option>${x}</option>`).join("")}</select>
   <div class="detail-actions"><button class="primary" onclick="addCompare('${v.id}');closeModal()">＋ Add to Compare</button><button onclick="saveVehicle('${v.id}')">♡ Save</button></div>
   ${v.official360?`<div class="official"><a class="view360" href="${v.official360}" target="_blank" rel="noopener">🔄 Open official 360° / configurator</a></div>`:""}
   ${v.interiorUrl?`<div class="official">🛋️ <a href="${v.interiorUrl}" target="_blank" rel="noopener">Open official interior & 360° page</a></div>`:""}
   <div class="source-note">${v.source}</div>
  </div>
 </div>
 <div class="detail-sections"><div class="tabs"><button class="tab active" onclick="detailTab('specs',this)">Specifications</button><button class="tab" onclick="detailTab('features',this)">Features</button><button class="tab" onclick="detailTab('gallery',this)">Gallery</button></div>
 <div id="detailPanel" class="tab-panel">${specPanel(v)}</div></div>`;
 document.getElementById("vehicleModal").classList.add("show");document.getElementById("vehicleModal").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";
}
function specPanel(v){return `<div class="spec-table">
 ${[["Engine",v.engines.join(" / ")],["Fuel",v.fuel],["Transmission",v.transmission],["Drivetrain",v.drive],["Seating",v.seats],["Mileage / Range",v.mileage],["Length",v.length],["Wheelbase",v.wheelbase],["Price",v.price]].map(x=>`<div class="spec-cell"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div>`}
function featurePanel(v){return `<div class="feature-list">${v.features.map(x=>`<div class="feature">✓ ${x}</div>`).join("")}</div>`}
function galleryPanel(v){return `<div class="feature-list">${v.gallery.map((x,i)=>`<div class="feature"><img src="${x}" style="width:100%;height:220px;object-fit:contain;background:#f0f1f2;border-radius:10px" onerror="safeImage(this)"><p style="margin-top:8px">${i?"Gallery view":"Main exterior view"}</p></div>`).join("")}</div>`}
function detailTab(tab,btn){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const v=getVehicle(document.querySelector(".modal-card")?.dataset?.id); /* fallback below */ const title=document.querySelector(".detail-info h2")?.textContent||"";const vv=[...vehicles,...bikes].find(x=>`${x.brand} ${x.name}`===title);document.getElementById("detailPanel").innerHTML=tab==="specs"?specPanel(vv):tab==="features"?featurePanel(vv):galleryPanel(vv)}
function changeDetailImage(src,btn){document.getElementById("detailMainImage").src=src;document.querySelectorAll(".thumbs button").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}
function selectColor(btn,name){
 document.querySelectorAll(".swatch").forEach(x=>x.classList.remove("active"));btn.classList.add("active");
 const overlay=document.getElementById("colorOverlay");
 const color=btn.style.backgroundColor || btn.style.background;
 if(overlay){overlay.style.background=color;overlay.style.opacity="0.38";}
 document.getElementById("selectedColor").textContent="Selected: "+name+" • visual colour preview";
}
function closeModal(){document.getElementById("vehicleModal").classList.remove("show");document.body.style.overflow=""}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});

function addCompare(id){if(compareIds.includes(id))return;if(compareIds.length>=2)compareIds.shift();compareIds.push(id);renderCompare();document.getElementById("compare").scrollIntoView({behavior:"smooth"})}
function removeCompare(id){compareIds=compareIds.filter(x=>x!==id);renderCompare()}
function renderCompare(){
 const slots=document.getElementById("compareSlots"), table=document.getElementById("compareTable"); 
 slots.innerHTML=[0,1].map(i=>{const v=getVehicle(compareIds[i]||"");return `<div class="compare-slot">${v?`<strong>${v.brand} ${v.name}</strong><span>${v.price} • ${v.engines[0]}</span> <button class="ghost" onclick="removeCompare('${v.id}')" style="float:right">Remove</button>`:"<strong>Empty comparison slot</strong><span>Add a vehicle using the Compare button.</span>"}</div>`}).join("");
 if(compareIds.length<2){table.innerHTML="";return}
 const a=getVehicle(compareIds[0]),b=getVehicle(compareIds[1]);
 const rows=[["Brand / Model",`${a.brand} ${a.name}`,`${b.brand} ${b.name}`],["Price",a.price,b.price],["Engine",a.engines.join(" / "),b.engines.join(" / ")],["Fuel",a.fuel,b.fuel],["Transmission",a.transmission,b.transmission],["Drivetrain",a.drive,b.drive],["Seats",a.seats,b.seats],["Mileage / Range",a.mileage,b.mileage],["Length",a.length,b.length],["Wheelbase",a.wheelbase,b.wheelbase]];
 table.innerHTML=`<table class="compare-table"><tr><th>Specification</th><th>${a.name}</th><th>${b.name}</th></tr>${rows.slice(1).map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join("")}</table>`;
}
function toggleFavourite(id,btn){btn.textContent=btn.textContent==="♡"?"♥":"♡";localStorage.setItem("fav_"+id,btn.textContent==="♥"?"1":"0")}
function saveVehicle(id){localStorage.setItem("saved_"+id,"1");alert("Saved to this browser.")}
render();
